export type City = { plaka: number; slug: string; name: string }

// Plaka sirasinda 81 il. slug = URL, name = ekranda gorunen ad.
export const CITIES: City[] = [
  { plaka: 1, slug: 'adana', name: 'Adana' },
  { plaka: 2, slug: 'adiyaman', name: 'Adıyaman' },
  { plaka: 3, slug: 'afyonkarahisar', name: 'Afyonkarahisar' },
  { plaka: 4, slug: 'agri', name: 'Ağrı' },
  { plaka: 5, slug: 'amasya', name: 'Amasya' },
  { plaka: 6, slug: 'ankara', name: 'Ankara' },
  { plaka: 7, slug: 'antalya', name: 'Antalya' },
  { plaka: 8, slug: 'artvin', name: 'Artvin' },
  { plaka: 9, slug: 'aydin', name: 'Aydın' },
  { plaka: 10, slug: 'balikesir', name: 'Balıkesir' },
  { plaka: 11, slug: 'bilecik', name: 'Bilecik' },
  { plaka: 12, slug: 'bingol', name: 'Bingöl' },
  { plaka: 13, slug: 'bitlis', name: 'Bitlis' },
  { plaka: 14, slug: 'bolu', name: 'Bolu' },
  { plaka: 15, slug: 'burdur', name: 'Burdur' },
  { plaka: 16, slug: 'bursa', name: 'Bursa' },
  { plaka: 17, slug: 'canakkale', name: 'Çanakkale' },
  { plaka: 18, slug: 'cankiri', name: 'Çankırı' },
  { plaka: 19, slug: 'corum', name: 'Çorum' },
  { plaka: 20, slug: 'denizli', name: 'Denizli' },
  { plaka: 21, slug: 'diyarbakir', name: 'Diyarbakır' },
  { plaka: 22, slug: 'edirne', name: 'Edirne' },
  { plaka: 23, slug: 'elazig', name: 'Elazığ' },
  { plaka: 24, slug: 'erzincan', name: 'Erzincan' },
  { plaka: 25, slug: 'erzurum', name: 'Erzurum' },
  { plaka: 26, slug: 'eskisehir', name: 'Eskişehir' },
  { plaka: 27, slug: 'gaziantep', name: 'Gaziantep' },
  { plaka: 28, slug: 'giresun', name: 'Giresun' },
  { plaka: 29, slug: 'gumushane', name: 'Gümüşhane' },
  { plaka: 30, slug: 'hakkari', name: 'Hakkari' },
  { plaka: 31, slug: 'hatay', name: 'Hatay' },
  { plaka: 32, slug: 'isparta', name: 'Isparta' },
  { plaka: 33, slug: 'mersin', name: 'Mersin' },
  { plaka: 34, slug: 'istanbul', name: 'İstanbul' },
  { plaka: 35, slug: 'izmir', name: 'İzmir' },
  { plaka: 36, slug: 'kars', name: 'Kars' },
  { plaka: 37, slug: 'kastamonu', name: 'Kastamonu' },
  { plaka: 38, slug: 'kayseri', name: 'Kayseri' },
  { plaka: 39, slug: 'kirklareli', name: 'Kırklareli' },
  { plaka: 40, slug: 'kirsehir', name: 'Kırşehir' },
  { plaka: 41, slug: 'kocaeli', name: 'Kocaeli' },
  { plaka: 42, slug: 'konya', name: 'Konya' },
  { plaka: 43, slug: 'kutahya', name: 'Kütahya' },
  { plaka: 44, slug: 'malatya', name: 'Malatya' },
  { plaka: 45, slug: 'manisa', name: 'Manisa' },
  { plaka: 46, slug: 'kahramanmaras', name: 'Kahramanmaraş' },
  { plaka: 47, slug: 'mardin', name: 'Mardin' },
  { plaka: 48, slug: 'mugla', name: 'Muğla' },
  { plaka: 49, slug: 'mus', name: 'Muş' },
  { plaka: 50, slug: 'nevsehir', name: 'Nevşehir' },
  { plaka: 51, slug: 'nigde', name: 'Niğde' },
  { plaka: 52, slug: 'ordu', name: 'Ordu' },
  { plaka: 53, slug: 'rize', name: 'Rize' },
  { plaka: 54, slug: 'sakarya', name: 'Sakarya' },
  { plaka: 55, slug: 'samsun', name: 'Samsun' },
  { plaka: 56, slug: 'siirt', name: 'Siirt' },
  { plaka: 57, slug: 'sinop', name: 'Sinop' },
  { plaka: 58, slug: 'sivas', name: 'Sivas' },
  { plaka: 59, slug: 'tekirdag', name: 'Tekirdağ' },
  { plaka: 60, slug: 'tokat', name: 'Tokat' },
  { plaka: 61, slug: 'trabzon', name: 'Trabzon' },
  { plaka: 62, slug: 'tunceli', name: 'Tunceli' },
  { plaka: 63, slug: 'sanliurfa', name: 'Şanlıurfa' },
  { plaka: 64, slug: 'usak', name: 'Uşak' },
  { plaka: 65, slug: 'van', name: 'Van' },
  { plaka: 66, slug: 'yozgat', name: 'Yozgat' },
  { plaka: 67, slug: 'zonguldak', name: 'Zonguldak' },
  { plaka: 68, slug: 'aksaray', name: 'Aksaray' },
  { plaka: 69, slug: 'bayburt', name: 'Bayburt' },
  { plaka: 70, slug: 'karaman', name: 'Karaman' },
  { plaka: 71, slug: 'kirikkale', name: 'Kırıkkale' },
  { plaka: 72, slug: 'batman', name: 'Batman' },
  { plaka: 73, slug: 'sirnak', name: 'Şırnak' },
  { plaka: 74, slug: 'bartin', name: 'Bartın' },
  { plaka: 75, slug: 'ardahan', name: 'Ardahan' },
  { plaka: 76, slug: 'igdir', name: 'Iğdır' },
  { plaka: 77, slug: 'yalova', name: 'Yalova' },
  { plaka: 78, slug: 'karabuk', name: 'Karabük' },
  { plaka: 79, slug: 'kilis', name: 'Kilis' },
  { plaka: 80, slug: 'osmaniye', name: 'Osmaniye' },
  { plaka: 81, slug: 'duzce', name: 'Düzce' },
]

const BY_SLUG = new Map(CITIES.map((c) => [c.slug, c]))

export function cityBySlug(slug: string): City | undefined {
  return BY_SLUG.get(slug)
}

export function cityName(slug: string): string {
  return BY_SLUG.get(slug)?.name ?? slug
}
